// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.2
// catalogDigest: sha256:e594f4b83ceb1ccda711e308dab22444cb4ddfcda30a892f5d4dd2751519a71c

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:e594f4b83ceb1ccda711e308dab22444cb4ddfcda30a892f5d4dd2751519a71c" as const;

export type PromptKey =
	| "greeting";

export type PromptValueMap = {
	"greeting": Record<string, never>;
};

export type PromptOutputMap = {
	"greeting": "text";
};

export type PromptMessageRoleMap = {
	"greeting": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
	PromptKey,
	PromptValueMap,
	PromptOutputMap,
	PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
