// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.3
// catalogDigest: sha256:b1d3599c51c23f643e8a11abb221bcb98b4bbb056e1e07f3605e165df259d560

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:b1d3599c51c23f643e8a11abb221bcb98b4bbb056e1e07f3605e165df259d560" as const;

export type PromptKey =
	| "greeting";

export type PromptValueMap = {
	"greeting": Record<string, never>;
};

export type PromptOutputMap = {
	"greeting": "text";
};

export type PromptMessageRoleMap = {
	"greeting": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
	PromptKey,
	PromptValueMap,
	PromptOutputMap,
	PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
