// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.2.0
// catalogDigest: sha256:216db0d9edcffb9b00b0904d7f0c0dbffb30173042d10714c61825aede97f4a0

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:216db0d9edcffb9b00b0904d7f0c0dbffb30173042d10714c61825aede97f4a0" as const;

export type PromptKey =
	| "greeting";

export type PromptValueMap = {
	"greeting": Record<string, never>;
};

export type PromptOutputMap = {
	"greeting": "text";
};

export type PromptMessageRoleMap = {
	"greeting": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
	PromptKey,
	PromptValueMap,
	PromptOutputMap,
	PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
