// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.2.0
// catalogDigest: sha256:2c25ed7d5a0acad52434190535d6cb2d7371f7407735caabfacb4d45fffded2d

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:2c25ed7d5a0acad52434190535d6cb2d7371f7407735caabfacb4d45fffded2d" as const;

export type PromptKey =
	| "codingAgent.identity";

export type PromptValueMap = {
	"codingAgent.identity": {
		"taskGoal": string;
	};
};

export type PromptOutputMap = {
	"codingAgent.identity": "text";
};

export type PromptMessageRoleMap = {
	"codingAgent.identity": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
	PromptKey,
	PromptValueMap,
	PromptOutputMap,
	PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
