// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.3
// catalogDigest: sha256:e8e8a8c839567f7e9fd4ce85f868c6ea45925efb088d24cacb8d98132eb5da88

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:e8e8a8c839567f7e9fd4ce85f868c6ea45925efb088d24cacb8d98132eb5da88" as const;

export type PromptKey =
	| "codingAgent.identity";

export type PromptValueMap = {
	"codingAgent.identity": {
		"taskGoal": string;
	};
};

export type PromptOutputMap = {
	"codingAgent.identity": "text";
};

export type PromptMessageRoleMap = {
	"codingAgent.identity": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
	PromptKey,
	PromptValueMap,
	PromptOutputMap,
	PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
	return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
