import type { S11tnextCatalogArtifact, S11tnextCompiledContext } from "s11tnext";
import { COMPILER_VERSION } from "s11tnext/compiler";

function compareCodeUnits(left: string, right: string): number {
	return left < right ? -1 : left > right ? 1 : 0;
}

function typeFor(variable: S11tnextCompiledContext["variables"][string]): string {
	if (variable.type === "json") return "JsonValue";
	return variable.type;
}

function fieldsFor(context: S11tnextCompiledContext, indent: string): string {
	return Object.keys(context.variables)
		.sort(compareCodeUnits)
		.map((name) => {
			const variable = context.variables[name]!;
			return `${indent}${indent}${JSON.stringify(name)}${variable.required ? "" : "?"}: ${typeFor(variable)};`;
		})
		.join("\n");
}

export function emitTypes(artifact: S11tnextCatalogArtifact, options: { indent?: string } = {}): string {
	const indent = options.indent ?? "\t";
	const canonicalKeys = Object.keys(artifact.contexts).sort(compareCodeUnits);
	const usesJson = Object.values(artifact.contexts).some((context) =>
		Object.values(context.variables).some((variable) => variable.type === "json"),
	);
	const keyUnion = canonicalKeys.map((key) => `${indent}| ${JSON.stringify(key)}`).join("\n");
	const values = canonicalKeys
		.map((key) => {
			const context = artifact.contexts[key]!;
			const fields = fieldsFor(context, indent);
			return fields.length === 0
				? `${indent}${JSON.stringify(key)}: Record<string, never>;`
				: `${indent}${JSON.stringify(key)}: {\n${fields}\n${indent}};`;
		})
		.join("\n");
	const outputs = canonicalKeys.map((key) => `${indent}${JSON.stringify(key)}: "text";`).join("\n");
	const roles = canonicalKeys
		.map((key) => `${indent}${JSON.stringify(key)}: ${JSON.stringify(artifact.contexts[key]!.messageRole)};`)
		.join("\n");
	return `// Generated by s11tnext-cli. Do not edit.\n// compilerVersion: ${COMPILER_VERSION}\n// catalogDigest: ${artifact.catalogDigest}\n\nimport type { CatalogContract${usesJson ? ", JsonValue" : ""} } from "s11tnext";\nimport { createCatalog } from "s11tnext";\n\nexport const expectedCatalogDigest = ${JSON.stringify(artifact.catalogDigest)} as const;\n\nexport type PromptKey =\n${keyUnion};\n\nexport type PromptValueMap = {\n${values}\n};\n\nexport type PromptOutputMap = {\n${outputs}\n};\n\nexport type PromptMessageRoleMap = {\n${roles}\n};\n\n/** @deprecated Use PromptKey. */\nexport type SystemContextKey = PromptKey;\n/** @deprecated Use PromptValueMap. */\nexport type SystemContextValueMap = PromptValueMap;\n/** @deprecated Use PromptOutputMap. */\nexport type SystemContextOutputMap = PromptOutputMap;\n\nexport type AppCatalogContract = CatalogContract<\n${indent}PromptKey,\n${indent}PromptValueMap,\n${indent}PromptOutputMap,\n${indent}PromptMessageRoleMap\n>;\n\nexport function createAppCatalog(artifact: unknown) {\n${indent}return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });\n}\n`;
}
